set_property SRC_FILE_INFO {cfile:x:/repositories/gen_heartbeat/sources/ip/ip_mmcm/ip_mmcm/ip_mmcm_in_context.xdc rfile:../../../../../sources/ip/ip_mmcm/ip_mmcm/ip_mmcm_in_context.xdc id:1 order:EARLY scoped_inst:inst_ip_mmcm} [current_design]
set_property SRC_FILE_INFO {cfile:X:/repositories/gen_heartbeat/constraints/pinout_zedboard.xdc rfile:../../../../../constraints/pinout_zedboard.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name OSC_100M [get_ports OSC_100M]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name inst_ip_mmcm/clk_out1 -source [get_pins inst_ip_mmcm/clk_in1] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins inst_ip_mmcm/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports OSC_100M]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports OSC_100M]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells inst_ip_mmcm]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst_ip_mmcm]
