# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/gen_heartbeat/constraints/pinout_zedboard.xdc

# IP: C:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/gen_heartbeat/sources/ip/ip_mmcm/ip_mmcm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_mmcm || ORIG_REF_NAME==ip_mmcm} -quiet] -quiet
